name: Spellcheck (German)

on:
  pull_request:
    branches:
      - '**'

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Spelling (German)
        uses: rojopolis/spellcheck-github-actions@0.51.0
        with:
          config_path: .spellcheck.yml
          task_name: Spellcheck
